### ISSUE TITLE
[1.12] Compressed Magical Essence Missing Recipe

### ISSUE THREAD

**Issue by MokahTGS** [SocraticPhoenix/ArcaneBags#1]
Looks like compressed magical essence is missing its recipe or just not hooked up to JEI.

**Comment by SocraticPhoenix** [comment]
Not hooked to JEI, or the recipe book. I might add that in the future, but the recipe is just a compression matrix + magical essence block. I'll leave this open to remind me :)

**Comment by MokahTGS** [comment]
I"fixed" it for now with Crafttweaker but eventually you should hook it up.

**Comment by SocraticPhoenix** [comment]
I'm planning on completely re-doing (and simplifying) the recipes, so there probably won't even be a compression matrix in the future, so I'm closing this for now, but it's not *fixed* quite yet.
